/**
 * SQLite 시절 `schema.ts` + `ensureColumn` 들을 합친 Postgres 초기 스키마 (22개 테이블).
 *
 * 1차 전환은 **타입을 보존**한다 — 날짜는 ISO 문자열(TEXT), 불리언은 0/1(INTEGER).
 * API 응답 모양을 그대로 두기 위해서다. timestamptz/boolean 정교화는 후속 마이그레이션 몫.
 *
 * - SQLite `AUTOINCREMENT` → `GENERATED BY DEFAULT AS IDENTITY`
 *   (BY DEFAULT 라 SQLite 데이터 이관 때 기존 번호를 그대로 넣을 수 있다)
 * - SQLite `ORDER BY rowid` 를 쓰던 테이블에는 삽입 순서용 `seq` 를 둔다
 * - id·시각처럼 정렬에 쓰는 TEXT 는 `COLLATE "C"` — SQLite 와 같은 바이트 순서
 * - `handle COLLATE NOCASE UNIQUE` → `lower(handle)` 유니크 인덱스
 */
export const sql = `
CREATE TABLE users (
  id TEXT COLLATE "C" PRIMARY KEY,
  handle TEXT NOT NULL,
  name TEXT NOT NULL,
  bio TEXT NOT NULL DEFAULT '',
  avatar TEXT,
  password_hash TEXT,
  notifications_enabled INTEGER NOT NULL DEFAULT 1,
  role TEXT NOT NULL DEFAULT 'user',
  suspended INTEGER NOT NULL DEFAULT 0,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE UNIQUE INDEX users_handle_lower ON users (lower(handle));

CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE shorts (
  id TEXT COLLATE "C" PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  author_id TEXT NOT NULL REFERENCES users(id),
  likes INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  views TEXT NOT NULL DEFAULT '0',
  video_url TEXT,
  thumb TEXT,
  gradient TEXT NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_shorts_author ON shorts(author_id);

CREATE TABLE comments (
  id TEXT COLLATE "C" PRIMARY KEY,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  short_id TEXT NOT NULL REFERENCES shorts(id) ON DELETE CASCADE,
  author TEXT NOT NULL,
  text TEXT NOT NULL,
  time TEXT NOT NULL,
  parent_id TEXT REFERENCES comments(id) ON DELETE CASCADE,
  author_id TEXT REFERENCES users(id)
);
CREATE INDEX idx_comments_short ON comments(short_id);
CREATE INDEX idx_comments_parent ON comments(parent_id);

CREATE TABLE chat_users (
  id TEXT PRIMARY KEY,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name TEXT NOT NULL,
  handle TEXT NOT NULL,
  avatar TEXT,
  last_message TEXT NOT NULL DEFAULT '',
  online INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE messages (
  id TEXT PRIMARY KEY,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  peer_id TEXT NOT NULL,
  type TEXT NOT NULL,
  content TEXT NOT NULL,
  is_image INTEGER NOT NULL DEFAULT 0,
  time TEXT NOT NULL
);
CREATE INDEX idx_messages_peer ON messages(peer_id);

CREATE TABLE faqs (
  id TEXT PRIMARY KEY,
  seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  question TEXT NOT NULL,
  answers TEXT NOT NULL
);

CREATE TABLE chatbot_docs (
  id TEXT PRIMARY KEY,
  owner TEXT NOT NULL,
  thread_key TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_chatbot_docs_owner ON chatbot_docs(owner);
CREATE INDEX idx_chatbot_docs_thread ON chatbot_docs(owner, thread_key);

CREATE TABLE chatbot_summaries (
  owner TEXT NOT NULL,
  thread_key TEXT NOT NULL,
  summary TEXT NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (owner, thread_key)
);

CREATE TABLE longform (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  video_url TEXT NOT NULL DEFAULT '',
  thumb TEXT,
  gradient TEXT NOT NULL,
  author_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_longform_author ON longform(author_id);

CREATE TABLE community_posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  author_id TEXT NOT NULL REFERENCES users(id),
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_community_author ON community_posts(author_id);

CREATE TABLE chatbot_threads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  model TEXT NOT NULL DEFAULT 'locals',
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_chatbot_threads_owner ON chatbot_threads(owner_id);

CREATE TABLE chatbot_messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id INTEGER NOT NULL REFERENCES chatbot_threads(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  attachments TEXT,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_chatbot_messages_thread ON chatbot_messages(thread_id);

CREATE TABLE conversations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id),
  target_name TEXT NOT NULL,
  target_handle TEXT NOT NULL,
  last_message TEXT NOT NULL DEFAULT '',
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_conversations_owner ON conversations(owner_id);

CREATE TABLE chat_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  content TEXT NOT NULL,
  is_image INTEGER NOT NULL DEFAULT 0,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_chat_lines_conversation ON chat_lines(conversation_id);

CREATE TABLE support_inquiries (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id),
  subject TEXT NOT NULL,
  body TEXT NOT NULL,
  admin_reply TEXT,
  replied_at TEXT COLLATE "C",
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_support_inquiries_owner ON support_inquiries(owner_id);

CREATE TABLE activity_notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id),
  category TEXT NOT NULL,
  message TEXT NOT NULL,
  href TEXT,
  read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_activity_notifications_owner ON activity_notifications(owner_id);

CREATE TABLE user_follows (
  follower_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  following_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (follower_id, following_id)
);
CREATE INDEX idx_user_follows_following ON user_follows(following_id);

CREATE TABLE user_blocks (
  blocker_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  blocked_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (blocker_id, blocked_id)
);

CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id TEXT NOT NULL REFERENCES users(id),
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_reports_target ON reports(target_type, target_id);

CREATE TABLE playlists (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL
);
CREATE INDEX idx_playlists_owner ON playlists(owner_id);

CREATE TABLE playlist_items (
  playlist_id INTEGER NOT NULL REFERENCES playlists(id) ON DELETE CASCADE,
  short_id TEXT NOT NULL REFERENCES shorts(id) ON DELETE CASCADE,
  added_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (playlist_id, short_id)
);
`;
